---
  - name: install a packages with yum and all dependence
    ansible.builtin.package:
      name:
        - graphviz
        - xinetd
        - check-mk-raw-2.1.0p38-el9-38.x86_64.rpm
      state: present
      disable_gpg_check: yes
