---
# tasks file for install_check_mk_raw
- name: Download Check_MK Raw
  import_tasks: download_cmk_raw.yml
  tags: download

- name: Install Check_MK Raw and dependences
  import_tasks: install_checkmk_raw.yml
  tags: checkmk_linux_install

