---
# tasks file for base-so
- name: Update on family 'Red-Hat' 
  become: yes
  import_tasks: dnf-update.yml
  when: ansible_facts['os_family'] == "RedHat"
  tags: update-red-hat
  
- name: Update on family 'Ubuntu'
  become: yes
  import_tasks: apt-update.yml
  when: ansible_facts['os_family'] == "Debian"
  tags: update-ubuntu

- name: Disable basics security
  become: yes
  import_tasks: disable_se.yml
  when: ansible_facts['os_family'] == "RedHat"
  tags: disable-security
    
