---
# tasks file for install-mariadb
  - name: start update dependences
    shell: sudo apt-get update -y
    tags: update-dep

  - name: install mariadb
    apt:
      name:
        - mariadb-server
      state: present
    register: installed
    tags: install-mariadb
 
  - name: Set a root mysql password
    become: yes
    shell: sudo mysql -e "set password = password('{{mysql_root_pass}}');"
    tags: set-root-mysql

  - name: copy a galera.cnf
    become: yes
    copy:
      src: 'galera_{{item.value.name}}.cnf'
      dest: /etc/mysql/mariadb.conf.d/galera.cnf
    when: "ansible_hostname == item.key"
    loop: "{{ lookup('dict', dbnodes) }}"
    tags: copy-cnf
  
  - name: stop a daemon service on linux
    ansible.builtin.service:
      name: mariadb
      state: stopped
    tags: stop-mariadb  

  - name: Execute a shell command
    ansible.builtin.shell: galera_new_cluster
    when: "ansible_hostname == 'dbnode1'"
    register: databases
    tags: create-galera-cluster
  
  - name: start a galera cluster nodes
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: true
    when: "ansible_hostname != 'dbnode1'"
    tags: start-galera-nodes  
  
  